// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/24/2026, 3:07:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/evgenii/My project/ai-musician/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/plugins/**/*.{js,ts,mjs}","/Users/evgenii/My project/ai-musician/app/composables/**/*.{js,ts,mjs}","/Users/evgenii/My project/ai-musician/app/utils/**/*.{js,ts,mjs}","/Users/evgenii/My project/ai-musician/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/evgenii/My project/ai-musician/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;